import { ReactElement, useState } from 'react';
import LoginLayout from '@components/LoginLayout';
import Head from 'next/head';
import { NextPageWithLayout } from './_app';

const Home: NextPageWithLayout = () => {
  const [login, setLogin] = useState({
    email: '',
    password: '',
  });

  // const { mutate, error, isLoading } = useLogin();

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setLogin({ ...login, [name]: value });
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    console.log('asdf');
    // mutate(login);
  };

  // if (error) {
  //   return <p>Oops! 에러가 발생했습니다</p>;
  // }

  return (
    <>
      <Head>
        <title>Preface</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>로그인</p>
      <form onSubmit={handleSubmit}>
        <p>E-MAIL</p>
        <input name="email" type="email" onChange={(e) => handleChange(e)} />
        <p>PASSWORD</p>
        <input
          name="password"
          type="password"
          onChange={(e) => handleChange(e)}
        />
        <button type="submit">제출</button>
      </form>
    </>
  );
};
export default Home;

Home.getLayout = function getLayout(page: ReactElement) {
  return <LoginLayout>{page}</LoginLayout>;
};
